{{- /* chezmoi:modify-template */ -}}
# chezmoi-managed:start
model = "gpt-5.4"
model_reasoning_effort = "high"
plan_mode_reasoning_effort = "xhigh"
service_tier = "fast"
web_search = "live"
personality = "none"
file_opener = "cursor"
#notify = ["bash", "/Users/shun/.codex/notify.sh"]
suppress_unstable_features_warning = true
js_repl_node_path = "~/.local/share/mise/installs/node/lts/bin/node"

[features]
unified_exec = true
shell_snapshot = true
multi_agent = true
prevent_idle_sleep = true
voice_transcription = true
js_repl = true
memories = true
image_generation = true

[agents]
max_threads = 24
max_depth = 4

[agents.explorer]
description = "Use `explorer` for specific codebase questions."
config_file = "./agents/explorer.toml"

[agents.worker]
description = "Use for execution and production work."
config_file = "./agents/worker.toml"

[sandbox_workspace_write]
network_access = true
writable_roots = ["~/.npm", "~/Library/pnpm", "~/Library/Caches", "~/.cache", "~/.local/state/mise", "~/.local/share/mise"]

[tui]
status_line = ["project-root", "git-branch", "context-remaining", "used-tokens", "total-input-tokens", "total-output-tokens"]

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp/oauth"

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true
# chezmoi-managed:end

{{- .chezmoi.stdin | replaceAllRegex "(?s)^# chezmoi-managed:start.*?# chezmoi-managed:end\n*" "\n\n" -}}
