#!/usr/bin/env sh

set -ue

DOTFILE_DIR="$(cd $(dirname $0)/..; pwd)"
cd "$DOTFILE_DIR"

# カレントディレクトリ下の.から始まる.git/下以外のファイルかシンボリックリンクを列挙
for file in $(find .* -not -path '../*' -not -path './*' -not -path '.git/*' \( -type f -o -type l \)); do
  # リンク元
  link_src="$DOTFILE_DIR/$file"
  # リンク先
  link_dst="$HOME/$file"

  # リンク先のディレクトリ
  link_dir="$(dirname "$link_dst")"
  # ディレクトリが存在しない場合は作成
  if [ ! -d "$link_dir" ]; then
    mkdir -p "$link_dir"
  fi

  # すでにシンボリックリンク以外のファイルが存在すればリネームして残す
  if [ -e "$link_dst" -a ! -L "$link_dst" ]; then
    mv "$link_dst" "$link_dst.old"
    echo "~/$file is renamed to ~/$file.old"
  fi

  # シンボリックリンクを貼る
  ln -fsn "$link_src" "$link_dst"
done
