#!/usr/bin/env sh

# config
asdf_version="v0.9.0"
fzf_version="0.30.0"

set -ue

SCRIPT_DIR="$(dirname $0)"
cd $SCRIPT_DIR

source "$SCRIPT_DIR/utils.sh"

export PATH="$HOME/.cargo/bin:$PATH"

# Rustのセットアップ
if ! has rustup; then
  curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path -c rust-src
fi

cat <<EOF > $HOME/.cargo/config.toml
[build]
rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = "thin"
codegen-units = 1
EOF

# キャッシュの設定
if ! has sccache; then
  cargo install sccache
fi
export RUSTC_WRAPPER="$(which sccache)"

# Rust製ツールのインストール
has cargo-add || cargo install cargo-edit
has cargo-watch || cargo install cargo-watch
has lsd || cargo install lsd
has bat || cargo install bat
has rg || cargo install ripgrep
has fd || cargo install fd-find
has delta || cargo install git-delta

# Rust Analyzerのインストール
if ! has rust-analyzer; then
  rust_analyzer_dir="$(mktemp -d)"
  git clone --depth=1 https://github.com/rust-analyzer/rust-analyzer.git $rust_analyzer_dir
  cd $rust_analyzer_dir
  $HOME/.cargo/bin/cargo xtask install --server
  cd $SCRIPT_DIR
  rm -rf $rust_analyzer_dir
fi


# asdfのインストール
if ! has asdf; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch $asdf_version
  set +ue
  source ~/.asdf/asdf.sh
  set -ue
  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  asdf plugin add golang https://github.com/kennyp/asdf-golang.git
  asdf install
fi

# Go製ツールのインストール
export GOPATH="$HOME/.local/share/go"
export GOBIN="$HOME/.local/bin"
has lazygit || go install github.com/jesseduffield/lazygit@latest
has ghq || go install github.com/x-motemen/ghq@latest

# fzfのインストール
if ! has fzf; then
  fzf_dir="$(mktemp -d)"
  git clone https://github.com/junegunn/fzf.git $fzf_dir --branch $fzf_version
  cd $fzf_dir
  make 
  cp target/fzf-* "$GOBIN/fzf"
  cd $SCRIPT_DIR
  rm -rf $fzf_dir
fi
